/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jonathan
 */
public class Jftelaprincipal extends javax.swing.JFrame {

    /**
     * Creates new form Jftelaprincipal
     */
    public Jftelaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jmcadastro = new javax.swing.JMenu();
        jmcliente = new javax.swing.JMenuItem();
        jmfornecedor = new javax.swing.JMenuItem();
        jmproduto = new javax.swing.JMenuItem();
        jmusuario = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmusuariovincular = new javax.swing.JMenuItem();
        jmusuarionovo = new javax.swing.JPopupMenu.Separator();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmrelatorio = new javax.swing.JMenu();
        jmsair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmcadastro.setText("Cadastros");

        jmcliente.setText("Clientes");
        jmcadastro.add(jmcliente);

        jmfornecedor.setText("Fornecedores");
        jmfornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmfornecedorActionPerformed(evt);
            }
        });
        jmcadastro.add(jmfornecedor);

        jmproduto.setText("Produtos");
        jmcadastro.add(jmproduto);

        jmusuario.setText("Usuários");

        jMenuItem1.setText("Novo");
        jmusuario.add(jMenuItem1);

        jmusuariovincular.setText("Vincular");
        jmusuario.add(jmusuariovincular);
        jmusuario.add(jmusuarionovo);

        jmcadastro.add(jmusuario);
        jmcadastro.add(jSeparator1);

        jMenuBar1.add(jmcadastro);

        jmrelatorio.setText("Relatórios");
        jMenuBar1.add(jmrelatorio);

        jmsair.setText("Sair");
        jmsair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmsairMouseClicked(evt);
            }
        });
        jMenuBar1.add(jmsair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 795, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmfornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmfornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmfornecedorActionPerformed

    private void jmsairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmsairMouseClicked
System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jmsairMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jftelaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jftelaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jftelaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jftelaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jftelaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu jmcadastro;
    private javax.swing.JMenuItem jmcliente;
    private javax.swing.JMenuItem jmfornecedor;
    private javax.swing.JMenuItem jmproduto;
    private javax.swing.JMenu jmrelatorio;
    private javax.swing.JMenu jmsair;
    private javax.swing.JMenu jmusuario;
    private javax.swing.JPopupMenu.Separator jmusuarionovo;
    private javax.swing.JMenuItem jmusuariovincular;
    // End of variables declaration//GEN-END:variables
}
